language: golang

services:
  - docker

env:
  - IMG=jessgreb/invest-ftw:$TRAVIS_COMMIT

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $IMG .
  - docker push $IMG

script:
  - docker run --entrypoint "/bin/ls" $IMG -al /app
