language: golang

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t invest-ftw:$TRAVIS_COMMIT .
  - docker push jessgreb/invest-ftw:$TRAVIS_COMMIT

script:
  - docker run --entrypoint "/bin/ls" invest -al /app
